name: Test

on:
  push:
    branches:
      - main
      - 'hotfix/**'
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'hotfix/**'
      - 'feature/**'

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.14' ]
    name: Test on Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Test
        env:
          GITHUB_CI: "GITHUB_CI"
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
          # bash <(curl -s https://codecov.io/bash)
